CREATE WAREHOUSE IF NOT EXISTS PMJAY_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND   = 60
    AUTO_RESUME    = TRUE
    COMMENT        = 'Warehouse for PM-JAY FWA Analytics Project';

    use warehouse PMJAY_WH;

    CREATE DATABASE IF NOT EXISTS PMJAY_FWA_DB
    COMMENT = 'Ayushman Bharat PM-JAY Fraud Waste Abuse Detection';

    Use database PMJAY_FWA_DB;

    create schema if not exists claims
    comment = 'claims trasanctions and reference data for PM-JAY FWA analysis';

    Use schema claims;

    CREATE OR REPLACE TABLE DIM_HOSPITALS (
    HOSPITAL_ID         VARCHAR(10)     NOT NULL PRIMARY KEY,
    HOSPITAL_NAME       VARCHAR(200)    NOT NULL,
    STATE               VARCHAR(50)     NOT NULL,
    CITY                VARCHAR(50)     NOT NULL,
    HOSPITAL_TYPE       VARCHAR(20)     NOT NULL,   -- Private / Government / Trust
    EMPANELMENT_DATE    DATE,
    IS_ACTIVE           CHAR(1)         DEFAULT 'Y',
    BED_CAPACITY        NUMBER(5,0),
    ICU_BEDS            NUMBER(4,0),
    IS_GOVT             CHAR(1),
    LOADED_AT           TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP()
);


CREATE OR REPLACE TABLE DIM_PACKAGES (
    PACKAGE_CODE        VARCHAR(10)     NOT NULL PRIMARY KEY,
    SPECIALTY_CODE      VARCHAR(5)      NOT NULL,
    SPECIALTY_NAME      VARCHAR(80)     NOT NULL,
    PROCEDURE_NAME      VARCHAR(200)    NOT NULL,
    APPROVED_RATE_INR   NUMBER(10,2)    NOT NULL,
    LOADED_AT           TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE DIM_BENEFICIARIES (
    BENEFICIARY_ID          VARCHAR(12)     NOT NULL PRIMARY KEY,
    ABHA_ID                 VARCHAR(20),
    FULL_NAME               VARCHAR(100)    NOT NULL,
    GENDER                  CHAR(1),
    AGE                     NUMBER(3,0),
    DOB                     DATE,
    STATE                   VARCHAR(50),
    CITY                    VARCHAR(50),
    PINCODE                 VARCHAR(6),
    RATION_CARD_NO          VARCHAR(20),
    ENROLLMENT_DATE         DATE,
    FAMILY_SIZE             NUMBER(2,0),
    ANNUAL_INCOME_BRACKET   VARCHAR(10),
    LOADED_AT               TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE FACT_CLAIMS (
    CLAIM_ID            VARCHAR(12)     NOT NULL PRIMARY KEY,
    BENEFICIARY_ID      VARCHAR(12)     NOT NULL,
    HOSPITAL_ID         VARCHAR(10)     NOT NULL,
    PACKAGE_CODE        VARCHAR(10)     NOT NULL,
    CLAIM_DATE          DATE            NOT NULL,
    DISCHARGE_DATE      DATE,
    LENGTH_OF_STAY      NUMBER(4,0),
    APPROVED_RATE_INR   NUMBER(10,2),
    BILLED_AMOUNT_INR   NUMBER(10,2),
    CLAIM_STATUS        VARCHAR(15),
    REJECTION_REASON    VARCHAR(100),
    PRE_AUTH_ID         VARCHAR(15),
    FINANCIAL_YEAR      VARCHAR(8),
    IS_FRAUD_FLAG       CHAR(1),
    LOADED_AT           TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP()
);



CREATE OR REPLACE STAGE PMJAY_STAGE
    FILE_FORMAT = (
        TYPE             = 'CSV'
        FIELD_OPTIONALLY_ENCLOSED_BY = '"'
        SKIP_HEADER      = 1
        NULL_IF          = ('', 'NULL', 'None')
        EMPTY_FIELD_AS_NULL = TRUE
    )
    COMMENT = 'Internal stage for PM-JAY project CSV files';

    

    CREATE OR REPLACE FILE FORMAT PMJAY_FWA_DB.CLAIMS.PMJAY_CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    RECORD_DELIMITER = '\n'
    SKIP_HEADER = 1
    NULL_IF = ('NULL', 'null', '')
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    TRIM_SPACE = TRUE;

   DESC TABLE PMJAY_FWA_DB.CLAIMS.DIM_HOSPITALS;

   COPY INTO PMJAY_FWA_DB.CLAIMS.DIM_HOSPITALS
    (HOSPITAL_ID, HOSPITAL_NAME, STATE, CITY, HOSPITAL_TYPE,
     EMPANELMENT_DATE, IS_ACTIVE, BED_CAPACITY, ICU_BEDS, IS_GOVT)
FROM @PMJAY_FWA_DB.CLAIMS.PMJAY_STAGE/dim_hospitals.csv
FILE_FORMAT = (FORMAT_NAME = 'PMJAY_FWA_DB.CLAIMS.PMJAY_CSV_FORMAT')
FORCE = TRUE;

COPY INTO PMJAY_FWA_DB.CLAIMS.DIM_PACKAGES
FROM @PMJAY_FWA_DB.CLAIMS.PMJAY_STAGE/dim_packages.csv
FILE_FORMAT = (FORMAT_NAME = 'PMJAY_FWA_DB.CLAIMS.PMJAY_CSV_FORMAT')
FORCE = TRUE;


DESC TABLE PMJAY_FWA_DB.CLAIMS.DIM_PACKAGES;

COPY INTO PMJAY_FWA_DB.CLAIMS.DIM_PACKAGES
    (PACKAGE_CODE, SPECIALTY_CODE, SPECIALTY_NAME, PROCEDURE_NAME, APPROVED_RATE_INR)
FROM @PMJAY_FWA_DB.CLAIMS.PMJAY_STAGE/dim_packages.csv
FILE_FORMAT = (FORMAT_NAME = 'PMJAY_FWA_DB.CLAIMS.PMJAY_CSV_FORMAT')
FORCE = TRUE;

COPY INTO PMJAY_FWA_DB.CLAIMS.DIM_BENEFICIARIES
FROM @PMJAY_FWA_DB.CLAIMS.PMJAY_STAGE/dim_beneficiaries.csv
FILE_FORMAT = (FORMAT_NAME = 'PMJAY_FWA_DB.CLAIMS.PMJAY_CSV_FORMAT')
FORCE = TRUE;

DESC TABLE PMJAY_FWA_DB.CLAIMS.DIM_BENEFICIARIES;

COPY INTO PMJAY_FWA_DB.CLAIMS.DIM_BENEFICIARIES
    (BENEFICIARY_ID, ABHA_ID, FULL_NAME, GENDER, AGE, DOB, 
     STATE, CITY, PINCODE, RATION_CARD_NO, ENROLLMENT_DATE, 
     FAMILY_SIZE, ANNUAL_INCOME_BRACKET)
FROM @PMJAY_FWA_DB.CLAIMS.PMJAY_STAGE/dim_beneficiaries.csv
FILE_FORMAT = (FORMAT_NAME = 'PMJAY_FWA_DB.CLAIMS.PMJAY_CSV_FORMAT')
FORCE = TRUE;

DESC TABLE PMJAY_FWA_DB.CLAIMS.FACT_CLAIMS;

ALTER TABLE PMJAY_FWA_DB.CLAIMS.FACT_CLAIMS 
MODIFY COLUMN FINANCIAL_YEAR VARCHAR(10);

COPY INTO PMJAY_FWA_DB.CLAIMS.FACT_CLAIMS
    (CLAIM_ID, BENEFICIARY_ID, HOSPITAL_ID, PACKAGE_CODE,
     CLAIM_DATE, DISCHARGE_DATE, LENGTH_OF_STAY,
     APPROVED_RATE_INR, BILLED_AMOUNT_INR, CLAIM_STATUS,
     REJECTION_REASON, PRE_AUTH_ID, FINANCIAL_YEAR, IS_FRAUD_FLAG)
FROM @PMJAY_FWA_DB.CLAIMS.PMJAY_STAGE/fact_claims_part1.csv
FILE_FORMAT = (FORMAT_NAME = 'PMJAY_FWA_DB.CLAIMS.PMJAY_CSV_FORMAT')
FORCE = TRUE;

COPY INTO PMJAY_FWA_DB.CLAIMS.FACT_CLAIMS
    (CLAIM_ID, BENEFICIARY_ID, HOSPITAL_ID, PACKAGE_CODE,
     CLAIM_DATE, DISCHARGE_DATE, LENGTH_OF_STAY,
     APPROVED_RATE_INR, BILLED_AMOUNT_INR, CLAIM_STATUS,
     REJECTION_REASON, PRE_AUTH_ID, FINANCIAL_YEAR, IS_FRAUD_FLAG)
FROM @PMJAY_FWA_DB.CLAIMS.PMJAY_STAGE/fact_claims_part2.csv
FILE_FORMAT = (FORMAT_NAME = 'PMJAY_FWA_DB.CLAIMS.PMJAY_CSV_FORMAT')
FORCE = TRUE;

SELECT COUNT(*) FROM PMJAY_FWA_DB.CLAIMS.FACT_CLAIMS;

TRUNCATE TABLE PMJAY_FWA_DB.CLAIMS.FACT_CLAIMS;

COPY INTO PMJAY_FWA_DB.CLAIMS.FACT_CLAIMS
    (CLAIM_ID, BENEFICIARY_ID, HOSPITAL_ID, PACKAGE_CODE,
     CLAIM_DATE, DISCHARGE_DATE, LENGTH_OF_STAY,
     APPROVED_RATE_INR, BILLED_AMOUNT_INR, CLAIM_STATUS,
     REJECTION_REASON, PRE_AUTH_ID, FINANCIAL_YEAR, IS_FRAUD_FLAG)
FROM @PMJAY_FWA_DB.CLAIMS.PMJAY_STAGE/fact_claims_part1.csv
FILE_FORMAT = (FORMAT_NAME = 'PMJAY_FWA_DB.CLAIMS.PMJAY_CSV_FORMAT')
FORCE = TRUE;

COPY INTO PMJAY_FWA_DB.CLAIMS.FACT_CLAIMS
    (CLAIM_ID, BENEFICIARY_ID, HOSPITAL_ID, PACKAGE_CODE,
     CLAIM_DATE, DISCHARGE_DATE, LENGTH_OF_STAY,
     APPROVED_RATE_INR, BILLED_AMOUNT_INR, CLAIM_STATUS,
     REJECTION_REASON, PRE_AUTH_ID, FINANCIAL_YEAR, IS_FRAUD_FLAG)
FROM @PMJAY_FWA_DB.CLAIMS.PMJAY_STAGE/fact_claims_part2.csv
FILE_FORMAT = (FORMAT_NAME = 'PMJAY_FWA_DB.CLAIMS.PMJAY_CSV_FORMAT')
FORCE = TRUE;

SELECT COUNT(*) FROM PMJAY_FWA_DB.CLAIMS.FACT_CLAIMS;

SELECT 'DIM_HOSPITALS'    AS table_name, COUNT(*) AS row_count FROM PMJAY_FWA_DB.CLAIMS.DIM_HOSPITALS
UNION ALL
SELECT 'DIM_PACKAGES',    COUNT(*) FROM PMJAY_FWA_DB.CLAIMS.DIM_PACKAGES
UNION ALL
SELECT 'DIM_BENEFICIARIES', COUNT(*) FROM PMJAY_FWA_DB.CLAIMS.DIM_BENEFICIARIES
UNION ALL
SELECT 'FACT_CLAIMS',     COUNT(*) FROM PMJAY_FWA_DB.CLAIMS.FACT_CLAIMS;

-- 6a: Providers Consistently Billing Above Approved Rate
SELECT 
    h.HOSPITAL_NAME,
    h.STATE,
    COUNT(*) AS total_claims,
    ROUND(AVG(f.BILLED_AMOUNT_INR), 2) AS avg_billed,
    ROUND(AVG(f.APPROVED_RATE_INR), 2) AS avg_approved,
    ROUND(AVG(f.BILLED_AMOUNT_INR - f.APPROVED_RATE_INR), 2) AS avg_overbill,
    ROUND(AVG(f.BILLED_AMOUNT_INR) * 100.0 / NULLIF(AVG(f.APPROVED_RATE_INR), 0), 2) AS billing_ratio_pct
FROM PMJAY_FWA_DB.CLAIMS.FACT_CLAIMS f
JOIN PMJAY_FWA_DB.CLAIMS.DIM_HOSPITALS h ON f.HOSPITAL_ID = h.HOSPITAL_ID
WHERE f.BILLED_AMOUNT_INR > f.APPROVED_RATE_INR
GROUP BY h.HOSPITAL_NAME, h.STATE
HAVING COUNT(*) > 100
ORDER BY avg_overbill DESC
LIMIT 20;


-- 6b: Duplicate Claim Detection
SELECT 
    f1.BENEFICIARY_ID,
    f1.PACKAGE_CODE,
    f1.HOSPITAL_ID,
    f1.CLAIM_DATE AS claim_date_1,
    f2.CLAIM_DATE AS claim_date_2,
    DATEDIFF('day', f1.CLAIM_DATE, f2.CLAIM_DATE) AS days_apart,
    f1.BILLED_AMOUNT_INR AS amount_1,
    f2.BILLED_AMOUNT_INR AS amount_2
FROM PMJAY_FWA_DB.CLAIMS.FACT_CLAIMS f1
JOIN PMJAY_FWA_DB.CLAIMS.FACT_CLAIMS f2
    ON f1.BENEFICIARY_ID = f2.BENEFICIARY_ID
    AND f1.PACKAGE_CODE = f2.PACKAGE_CODE
    AND f1.CLAIM_DATE < f2.CLAIM_DATE
    AND DATEDIFF('day', f1.CLAIM_DATE, f2.CLAIM_DATE) <= 30
WHERE f1.CLAIM_ID != f2.CLAIM_ID
ORDER BY days_apart
LIMIT 20;

-- 6c: Phantom Surgery Detection (impossible length of stay)
SELECT 
    f.CLAIM_ID,
    h.HOSPITAL_NAME,
    h.STATE,
    p.PROCEDURE_NAME,
    f.CLAIM_DATE,
    f.DISCHARGE_DATE,
    f.LENGTH_OF_STAY,
    f.BILLED_AMOUNT_INR
FROM PMJAY_FWA_DB.CLAIMS.FACT_CLAIMS f
JOIN PMJAY_FWA_DB.CLAIMS.DIM_HOSPITALS h ON f.HOSPITAL_ID = h.HOSPITAL_ID
JOIN PMJAY_FWA_DB.CLAIMS.DIM_PACKAGES p ON f.PACKAGE_CODE = p.PACKAGE_CODE
WHERE f.LENGTH_OF_STAY = 0
   OR (f.DISCHARGE_DATE < f.CLAIM_DATE)
   OR (f.LENGTH_OF_STAY > 30)
ORDER BY f.LENGTH_OF_STAY DESC
LIMIT 20;

-- 6d: Ghost Beneficiary Detection (claiming from multiple states)
SELECT 
    f.BENEFICIARY_ID,
    b.FULL_NAME,
    b.STATE AS registered_state,
    COUNT(DISTINCT h.STATE) AS states_claimed_from,
    COUNT(*) AS total_claims,
    SUM(f.BILLED_AMOUNT_INR) AS total_billed,
    LISTAGG(DISTINCT h.STATE, ', ') AS claim_states
FROM PMJAY_FWA_DB.CLAIMS.FACT_CLAIMS f
JOIN PMJAY_FWA_DB.CLAIMS.DIM_BENEFICIARIES b ON f.BENEFICIARY_ID = b.BENEFICIARY_ID
JOIN PMJAY_FWA_DB.CLAIMS.DIM_HOSPITALS h ON f.HOSPITAL_ID = h.HOSPITAL_ID
GROUP BY f.BENEFICIARY_ID, b.FULL_NAME, b.STATE
HAVING COUNT(DISTINCT h.STATE) >= 3
ORDER BY states_claimed_from DESC, total_billed DESC
LIMIT 20;

-- 6e: Rolling Fraud Rate by Hospital (Window Function)
SELECT 
    HOSPITAL_ID,
    CLAIM_DATE,
    CLAIM_STATUS,
    IS_FRAUD_FLAG,
    COUNT(*) OVER (PARTITION BY HOSPITAL_ID 
                   ORDER BY CLAIM_DATE 
                   ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS rolling_30day_claims,
    SUM(CASE WHEN IS_FRAUD_FLAG = 'Y' THEN 1 ELSE 0 END) 
        OVER (PARTITION BY HOSPITAL_ID 
              ORDER BY CLAIM_DATE 
              ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) AS rolling_fraud_count,
    ROUND(SUM(CASE WHEN IS_FRAUD_FLAG = 'Y' THEN 1 ELSE 0 END) 
        OVER (PARTITION BY HOSPITAL_ID 
              ORDER BY CLAIM_DATE 
              ROWS BETWEEN 29 PRECEDING AND CURRENT ROW) * 100.0 /
    NULLIF(COUNT(*) OVER (PARTITION BY HOSPITAL_ID 
                          ORDER BY CLAIM_DATE 
                          ROWS BETWEEN 29 PRECEDING AND CURRENT ROW), 0), 2) AS rolling_fraud_pct
FROM PMJAY_FWA_DB.CLAIMS.FACT_CLAIMS
ORDER BY HOSPITAL_ID, CLAIM_DATE
LIMIT 20;


-- 6f: CTE-Based Suspicious Claim Summary
WITH fraud_summary AS (
    SELECT 
        h.STATE,
        h.HOSPITAL_TYPE,
        COUNT(*) AS total_claims,
        SUM(CASE WHEN f.IS_FRAUD_FLAG = 'Y' THEN 1 ELSE 0 END) AS fraud_claims,
        SUM(f.BILLED_AMOUNT_INR) AS total_billed,
        SUM(CASE WHEN f.IS_FRAUD_FLAG = 'Y' THEN f.BILLED_AMOUNT_INR ELSE 0 END) AS fraud_amount
    FROM PMJAY_FWA_DB.CLAIMS.FACT_CLAIMS f
    JOIN PMJAY_FWA_DB.CLAIMS.DIM_HOSPITALS h ON f.HOSPITAL_ID = h.HOSPITAL_ID
    GROUP BY h.STATE, h.HOSPITAL_TYPE
)
SELECT 
    STATE,
    HOSPITAL_TYPE,
    total_claims,
    fraud_claims,
    ROUND(fraud_claims * 100.0 / NULLIF(total_claims, 0), 2) AS fraud_rate_pct,
    ROUND(total_billed / 1000000, 2) AS total_billed_millions,
    ROUND(fraud_amount / 1000000, 2) AS fraud_amount_millions
FROM fraud_summary
WHERE fraud_claims > 0
ORDER BY fraud_rate_pct DESC
LIMIT 20;

-- 6g: Overall Fraud Financial Impact Summary
SELECT
    COUNT(*) AS total_claims,
    SUM(CASE WHEN IS_FRAUD_FLAG = 'Y' THEN 1 ELSE 0 END) AS total_fraud_claims,
    ROUND(SUM(CASE WHEN IS_FRAUD_FLAG = 'Y' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS overall_fraud_rate_pct,
    ROUND(SUM(BILLED_AMOUNT_INR) / 10000000, 2) AS total_billed_crores,
    ROUND(SUM(CASE WHEN IS_FRAUD_FLAG = 'Y' THEN BILLED_AMOUNT_INR ELSE 0 END) / 10000000, 2) AS fraud_amount_crores,
    ROUND(SUM(CASE WHEN IS_FRAUD_FLAG = 'Y' THEN BILLED_AMOUNT_INR ELSE 0 END) * 100.0 / NULLIF(SUM(BILLED_AMOUNT_INR), 0), 2) AS fraud_amount_pct
FROM PMJAY_FWA_DB.CLAIMS.FACT_CLAIMS;

-- Section 7a: RBAC
CREATE ROLE IF NOT EXISTS PMJAY_ANALYST;
CREATE ROLE IF NOT EXISTS PMJAY_AUDITOR;
CREATE ROLE IF NOT EXISTS PMJAY_ADMIN;

GRANT ROLE PMJAY_ANALYST TO ROLE SYSADMIN;
GRANT ROLE PMJAY_AUDITOR TO ROLE SYSADMIN;
GRANT ROLE PMJAY_ADMIN TO ROLE SYSADMIN;

GRANT USAGE ON WAREHOUSE PMJAY_WH TO ROLE PMJAY_ANALYST;
GRANT USAGE ON WAREHOUSE PMJAY_WH TO ROLE PMJAY_AUDITOR;
GRANT USAGE ON DATABASE PMJAY_FWA_DB TO ROLE PMJAY_ANALYST;
GRANT USAGE ON DATABASE PMJAY_FWA_DB TO ROLE PMJAY_AUDITOR;
GRANT USAGE ON SCHEMA PMJAY_FWA_DB.CLAIMS TO ROLE PMJAY_ANALYST;
GRANT USAGE ON SCHEMA PMJAY_FWA_DB.CLAIMS TO ROLE PMJAY_AUDITOR;
GRANT SELECT ON ALL TABLES IN SCHEMA PMJAY_FWA_DB.CLAIMS TO ROLE PMJAY_AUDITOR;
GRANT SELECT ON TABLE PMJAY_FWA_DB.CLAIMS.FACT_CLAIMS TO ROLE PMJAY_ANALYST;

-- Section 7b: Row Access Policy
CREATE OR REPLACE ROW ACCESS POLICY PMJAY_FWA_DB.CLAIMS.state_access_policy
AS (state_col VARCHAR) RETURNS BOOLEAN ->
    CASE
        WHEN CURRENT_ROLE() = 'PMJAY_AUDITOR' THEN TRUE
        WHEN CURRENT_ROLE() = 'PMJAY_ANALYST' 
            AND state_col = 'Karnataka' THEN TRUE
        ELSE FALSE
    END;

ALTER TABLE PMJAY_FWA_DB.CLAIMS.DIM_HOSPITALS
    ADD ROW ACCESS POLICY PMJAY_FWA_DB.CLAIMS.state_access_policy ON (STATE);

    -- Section 7c: Dynamic Data Masking
CREATE OR REPLACE MASKING POLICY PMJAY_FWA_DB.CLAIMS.mask_beneficiary_name
AS (val VARCHAR) RETURNS VARCHAR ->
    CASE
        WHEN CURRENT_ROLE() IN ('PMJAY_AUDITOR', 'PMJAY_ADMIN') THEN val
        ELSE '***MASKED***'
    END;

CREATE OR REPLACE MASKING POLICY PMJAY_FWA_DB.CLAIMS.mask_ration_card
AS (val VARCHAR) RETURNS VARCHAR ->
    CASE
        WHEN CURRENT_ROLE() IN ('PMJAY_AUDITOR', 'PMJAY_ADMIN') THEN val
        ELSE LEFT(val, 4) || '********'
    END;

ALTER TABLE PMJAY_FWA_DB.CLAIMS.DIM_BENEFICIARIES
    MODIFY COLUMN FULL_NAME 
    SET MASKING POLICY PMJAY_FWA_DB.CLAIMS.mask_beneficiary_name;

ALTER TABLE PMJAY_FWA_DB.CLAIMS.DIM_BENEFICIARIES
    MODIFY COLUMN RATION_CARD_NO 
    SET MASKING POLICY PMJAY_FWA_DB.CLAIMS.mask_ration_card;

    -- Section 8a: Fraud Suspects View
CREATE OR REPLACE VIEW PMJAY_FWA_DB.CLAIMS.VW_FRAUD_SUSPECTS AS
SELECT 
    f.CLAIM_ID,
    f.CLAIM_DATE,
    h.HOSPITAL_NAME,
    h.STATE,
    h.HOSPITAL_TYPE,
    b.FULL_NAME AS beneficiary_name,
    b.STATE AS beneficiary_state,
    p.PROCEDURE_NAME,
    f.LENGTH_OF_STAY,
    f.APPROVED_RATE_INR,
    f.BILLED_AMOUNT_INR,
    ROUND(f.BILLED_AMOUNT_INR - f.APPROVED_RATE_INR, 2) AS overbill_amount,
    f.CLAIM_STATUS,
    f.IS_FRAUD_FLAG
FROM PMJAY_FWA_DB.CLAIMS.FACT_CLAIMS f
JOIN PMJAY_FWA_DB.CLAIMS.DIM_HOSPITALS h ON f.HOSPITAL_ID = h.HOSPITAL_ID
JOIN PMJAY_FWA_DB.CLAIMS.DIM_BENEFICIARIES b ON f.BENEFICIARY_ID = b.BENEFICIARY_ID
JOIN PMJAY_FWA_DB.CLAIMS.DIM_PACKAGES p ON f.PACKAGE_CODE = p.PACKAGE_CODE
WHERE f.IS_FRAUD_FLAG = 'Y'
   OR f.BILLED_AMOUNT_INR > f.APPROVED_RATE_INR
   OR f.LENGTH_OF_STAY = 0;

-- Section 8b: Provider Summary View
CREATE OR REPLACE VIEW PMJAY_FWA_DB.CLAIMS.VW_PROVIDER_SUMMARY AS
SELECT 
    h.HOSPITAL_ID,
    h.HOSPITAL_NAME,
    h.STATE,
    h.HOSPITAL_TYPE,
    h.IS_GOVT,
    COUNT(*) AS total_claims,
    SUM(CASE WHEN f.IS_FRAUD_FLAG = 'Y' THEN 1 ELSE 0 END) AS fraud_claims,
    ROUND(SUM(CASE WHEN f.IS_FRAUD_FLAG = 'Y' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS fraud_rate_pct,
    ROUND(SUM(f.BILLED_AMOUNT_INR) / 100000, 2) AS total_billed_lakhs,
    ROUND(AVG(f.BILLED_AMOUNT_INR), 2) AS avg_claim_amount
FROM PMJAY_FWA_DB.CLAIMS.FACT_CLAIMS f
JOIN PMJAY_FWA_DB.CLAIMS.DIM_HOSPITALS h ON f.HOSPITAL_ID = h.HOSPITAL_ID
GROUP BY h.HOSPITAL_ID, h.HOSPITAL_NAME, h.STATE, h.HOSPITAL_TYPE, h.IS_GOVT;


-- ============================================================
-- SECTION 9: TIME TRAVEL DEMO
-- Shows Snowflake's ability to query and recover past data
-- ============================================================

-- Step 1: Check current row count (baseline)
SELECT COUNT(*) AS current_count FROM PMJAY_FWA_DB.CLAIMS.FACT_CLAIMS;

-- Step 2: Record the current timestamp BEFORE making changes
-- Save this value — you'll use it to travel back
SET time_before_delete = CURRENT_TIMESTAMP();
SELECT $time_before_delete;

-- Step 3: Simulate an accidental deletion
-- (Delete Karnataka fraud claims as if a junior analyst made an error)
DELETE FROM PMJAY_FWA_DB.CLAIMS.FACT_CLAIMS
WHERE IS_FRAUD_FLAG = 'Y'
  AND CLAIM_ID IN (
      SELECT f.CLAIM_ID
      FROM PMJAY_FWA_DB.CLAIMS.FACT_CLAIMS f
      JOIN PMJAY_FWA_DB.CLAIMS.DIM_HOSPITALS h ON f.HOSPITAL_ID = h.HOSPITAL_ID
      WHERE h.STATE = 'Karnataka'
        AND f.IS_FRAUD_FLAG = 'Y'
      LIMIT 500
  );

-- Step 4: Confirm rows are gone
SELECT COUNT(*) AS count_after_delete FROM PMJAY_FWA_DB.CLAIMS.FACT_CLAIMS;

-- Step 5: Use Time Travel to query data AS IT WAS before deletion
SELECT COUNT(*) AS count_before_delete
FROM PMJAY_FWA_DB.CLAIMS.FACT_CLAIMS
AT (TIMESTAMP => $time_before_delete);

-- Step 6: Recover the deleted rows using Time Travel
INSERT INTO PMJAY_FWA_DB.CLAIMS.FACT_CLAIMS
    (CLAIM_ID, BENEFICIARY_ID, HOSPITAL_ID, PACKAGE_CODE,
     CLAIM_DATE, DISCHARGE_DATE, LENGTH_OF_STAY,
     APPROVED_RATE_INR, BILLED_AMOUNT_INR, CLAIM_STATUS,
     REJECTION_REASON, PRE_AUTH_ID, FINANCIAL_YEAR, IS_FRAUD_FLAG)
SELECT 
    CLAIM_ID, BENEFICIARY_ID, HOSPITAL_ID, PACKAGE_CODE,
    CLAIM_DATE, DISCHARGE_DATE, LENGTH_OF_STAY,
    APPROVED_RATE_INR, BILLED_AMOUNT_INR, CLAIM_STATUS,
    REJECTION_REASON, PRE_AUTH_ID, FINANCIAL_YEAR, IS_FRAUD_FLAG
FROM PMJAY_FWA_DB.CLAIMS.FACT_CLAIMS
AT (TIMESTAMP => $time_before_delete)
WHERE CLAIM_ID NOT IN (SELECT CLAIM_ID FROM PMJAY_FWA_DB.CLAIMS.FACT_CLAIMS);

-- Step 7: Confirm full recovery
SELECT COUNT(*) AS count_after_recovery FROM PMJAY_FWA_DB.CLAIMS.FACT_CLAIMS;

-- Step 8: Check Time Travel retention setting on this table
SHOW PARAMETERS LIKE 'DATA_RETENTION_TIME_IN_DAYS' IN TABLE PMJAY_FWA_DB.CLAIMS.FACT_CLAIMS;

ALTER WAREHOUSE PMJAY_WH RESUME;
SELECT CURRENT_WAREHOUSE();


-- Switch to auditor role to bypass the row access policy
USE ROLE PMJAY_AUDITOR;

SELECT * FROM PMJAY_FWA_DB.CLAIMS.VW_PROVIDER_SUMMARY LIMIT 10;

-- Now test the view
SELECT * FROM PMJAY_FWA_DB.CLAIMS.VW_PROVIDER_SUMMARY LIMIT 10;

SELECT * FROM PMJAY_FWA_DB.CLAIMS.VW_FRAUD_SUSPECTS LIMIT 50000;

SELECT * FROM PMJAY_FWA_DB.CLAIMS.VW_PROVIDER_SUMMARY;